Document: ndn-lintian-profile
Title: Debian ndn-lintian-profile Manual
Author: <insert document author here>
Abstract: This manual describes what ndn-lintian-profile is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ndn-lintian-profile/ndn-lintian-profile.sgml.gz

Format: postscript
Files: /usr/share/doc/ndn-lintian-profile/ndn-lintian-profile.ps.gz

Format: text
Files: /usr/share/doc/ndn-lintian-profile/ndn-lintian-profile.text.gz

Format: HTML
Index: /usr/share/doc/ndn-lintian-profile/html/index.html
Files: /usr/share/doc/ndn-lintian-profile/html/*.html
